version: '3.9'

services:
  navlens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navlens
    volumes:
      - ./navlens-data:/app/data
    environment:
      - NUXT_PUBLIC_AUTH_JS_BASE_URL=http://localhost:3000 # csrf origin
    ports:
      - 3000:3000
    restart: always
