version: '3.9'

services:
  navlens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navlens
    volumes:
      - ./navlens-data:/app/data
    ports:
      - 3000:3000
    restart: always
